### ISSUE TITLE
Do not mark keys as missing if they have been removed from the base locale

### ISSUE THREAD

**Issue by daniel-memo-ict** [boxblinkracer/phpunuhi#57] opened 2024-09-04 10:00 UTC
Consider the following snippet files:

en-GB, marked as base locale:
```json
{
  "foo": "bar",
  "key": "value"
}
```

nl-NL:
```json
{
  "foo": "bar",
  "key": "waarde",
  "remove": "dit"
}
```

The remove key has been removed from the base locale, perhaps because it's no longer necessary, however when running validate it will tell me I'm missing this key instead of telling me to remove it from the other locales.

I would like to see this changed, perhaps by adding an option to the validate command, where it will tell me to remove the keys that are not present in the base locale.

**Comment by boxblinkracer** [comment] 2024-11-03 10:40
hi
thanks for this

i think this is then the task of the dev to figure out this is important

its like a unit test is broken
is it because its just broken or because the requirements have changed

whats your opinion on that?

**Comment by griesi007** [comment] 2024-11-11 16:27
@boxblinkracer regarding your question. Probably it´s about making removing of keys easier. It would be great if this could be supported meaning I can remove the key in the base locale and phpunuhi will remove the obsolete keys in the translations. manually removing keys in all files is unnecessary tedious.

**Comment by daniels1989** [comment] 2024-11-13 10:29
> @boxblinkracer regarding your question. Probably it´s about making removing of keys easier. It would be great if this could be supported meaning I can remove the key in the base locale and phpunuhi will remove the obsolete keys in the translations. manually removing keys in all files is unnecessary tedious.

Exactly this. The validate command would currently mark keys that were removed from the base locale as "missing", even though ideally I would like to see them marked as "deprecated" or "removed" in the locales. The command wouldn't necessarily have to delete them automatically, but a separate command for that would be nice.

**Comment by boxblinkracer** [comment] 2024-11-13 10:45
thanks 

yeah there is another PR which makes more sense to delete
so the fix:mess would be a good one

so if a base locale is defined, fix mess could remove those keys

the other thing is the validation in combination with a base locale where a key has been removed
i have a bad feeling officially marking it as deprecated
because the reason why this test tools exist is because developers make bugs
so if a dev removes a key from the base locale on day 1 of coding, and on day 3 before doing the PR, phpunuhi tells him the keys are deprecated, he starts to remove those in other languages...but what actually happens is, that he (maybe out of accident) just removed it from the base locale which was wrong
...so with that in mind, for me as testing-tool it's a bit risky to say "you can remove it because its deprecated", i have a better feeling with, something is different, please check it out. but maybe i can add a hint that the base locale is missing and that it might can get removed?

what is your opinion on these ideas with fix:mess and validate?

**Comment by daniels1989** [comment] 2024-11-13 10:49
Yeah that would be fine. Just something that says "Hey this has been removed from the base locale, please check if that's correct." And if it was intended to be removed they can run fix:mess to have it be removed instead of doing it manually.

**Comment by boxblinkracer** [comment] 2024-11-13 10:55
perfect, i like it 
thanks for that idea :)

**Comment by boxblinkracer** [comment] 2024-11-13 16:48
more and more i think this is a brilliant adoption, if one is using base locale settings

<img width="1692" alt="Screenshot 2024-11-13 at 17 47 07" src="https://github.com/user-attachments/assets/6637e53e-5733-4c21-9b0f-b2fdd42a6a87">

**Comment by boxblinkracer** [comment] 2024-11-13 19:37
alright so this has been done (validation part)
the fix:mess will be done using the other issue (as part of another feature)

**Closed as completed** 2024-11-20 12:23 UTC
Labels: Feature Request, Released
